import Foundation

struct ClientBindingEmitter {
  let plan: ClientBindingPlan

  func emit() throws {
    let fileManager = FileManager.default
    if fileManager.fileExists(atPath: plan.outputRoot.path) {
      try fileManager.removeItem(at: plan.outputRoot)
    }
    try fileManager.createDirectory(at: plan.outputRoot, withIntermediateDirectories: true)

    for surface in Surface.allCases {
      try writeBindings(for: surface)
    }
    try writeMethodPolicy()
  }

  private func writeMethodPolicy() throws {
    let outputURL = plan.outputRoot
      .appendingPathComponent("CodexAppServerClient+MethodPolicy.swift")
    let deniedMethods = plan.adoption.rawDeniedMethods(for: plan.bindings)
      .map { "\"\(SwiftNames.stringLiteral($0).dropFirst().dropLast())\"" }
      .joined(separator: ",\n")
    let source = """
      // Generated by codex-app-server-protocol-generator. Do not edit.
      // Source: Vendor/CodexAppServerProtocolSchema/method-adoption.json.

      import Foundation

      extension CodexAppServerConnection {
        static let rawMethodDenyList: Set<String> = [
      \(deniedMethods.indented(by: 4))
        ]
      }

      """

    try source.write(to: outputURL, atomically: true, encoding: .utf8)
  }

  private func writeBindings(for surface: Surface) throws {
    let outputURL = plan.outputRoot
      .appendingPathComponent("CodexAppServerClient+\(surface.namespaceName)Bindings.swift")
    let bindings = plan.bindings.filter { $0.surface == surface }

    let source = """
      // Generated by codex-app-server-protocol-generator. Do not edit.
      // Source: Vendor/CodexAppServerProtocolSchema/\(surface.rawValue)/json/ClientRequest.json

      import CodexAppServerProtocol

      extension CodexAppServerConnection {
      \(bindings.map { render($0, surface: surface) }.joined(separator: "\n\n").indented(by: 2))
      }

      """

    try source.write(to: outputURL, atomically: true, encoding: .utf8)
  }

  private func render(_ binding: ClientBinding, surface: Surface) -> String {
    let namespace = surface.generatedNamespace
    let method = SwiftNames.stringLiteral(binding.method)
    if let paramsTypeName = binding.paramsTypeName {
      let optionalMarker = binding.paramsIsOptional ? "?" : ""
      let defaultExpression = binding.paramsDefaultExpression.map { " = \($0)" } ?? ""
      return """
        public func \(binding.functionName)(
          _ params: \(namespace).\(paramsTypeName)\(optionalMarker)\(defaultExpression)
        ) async throws -> \(namespace).\(binding.responseTypeName) {
          try await sendStableRequest(
            method: \(method),
            params: params,
            responseType: \(namespace).\(binding.responseTypeName).self
          )
        }
        """
    }

    return """
      public func \(binding.functionName)() async throws -> \(namespace).\(binding.responseTypeName) {
        try await sendStableRequest(
          method: \(method),
          responseType: \(namespace).\(binding.responseTypeName).self
        )
      }
      """
  }
}
