import Foundation

struct SwiftEmitter {
  let plan: GenerationPlan

  func emit() throws {
    let fileManager = FileManager.default
    if fileManager.fileExists(atPath: plan.outputRoot.path) {
      try fileManager.removeItem(at: plan.outputRoot)
    }
    try fileManager.createDirectory(at: plan.outputRoot, withIntermediateDirectories: true)

    try writeRootNamespaceFile()
    for surface in Surface.allCases {
      try writeSupportFile(for: surface)
    }

    for entry in plan.entries {
      let outputURL = plan.outputRoot.appendingPathComponent(entry.outputRelativePath)
      try fileManager.createDirectory(
        at: outputURL.deletingLastPathComponent(),
        withIntermediateDirectories: true
      )
      let source = try SurfaceEmitter(surface: entry.surface, entry: entry).emit()
      try source.write(to: outputURL, atomically: true, encoding: .utf8)
    }
  }

  private func writeRootNamespaceFile() throws {
    let outputURL = plan.outputRoot.appendingPathComponent("CodexAppServerProtocol.swift")
    let source = """
      // Generated by codex-app-server-protocol-generator. Do not edit.
      // Source: Vendor/CodexAppServerProtocolSchema

      import Foundation

      public enum CodexAppServerProtocol {}

      """

    try source.write(to: outputURL, atomically: true, encoding: .utf8)
  }

  private func writeSupportFile(for surface: Surface) throws {
    let outputURL = plan.outputRoot
      .appendingPathComponent(surface == .stable ? "Stable" : "Experimental")
      .appendingPathComponent("CodexAppServerProtocol+\(surface.namespaceName).swift")

    try FileManager.default.createDirectory(
      at: outputURL.deletingLastPathComponent(),
      withIntermediateDirectories: true
    )

    let source = """
      // Generated by codex-app-server-protocol-generator. Do not edit.
      // Source: Vendor/CodexAppServerProtocolSchema/\(surface.rawValue)/json

      import Foundation

      extension CodexAppServerProtocol {
        public enum \(surface.namespaceName) {}
      }

      extension \(surface.generatedNamespace) {
        public enum JSONNumber: Equatable, Sendable, ExpressibleByIntegerLiteral, ExpressibleByFloatLiteral {
          public typealias IntegerLiteralType = Int64
          public typealias FloatLiteralType = Double

          case integer(Int64)
          case decimal(Decimal)

          public init(integerLiteral value: Int64) {
            self = .integer(value)
          }

          public init(floatLiteral value: Double) {
            self = .decimal(Decimal(value))
          }
        }

        public indirect enum JSONValue: Codable, Equatable, Sendable {
          case null
          case bool(Bool)
          case number(JSONNumber)
          case string(String)
          case array([JSONValue])
          case object([String: JSONValue])

          public init(from decoder: Decoder) throws {
            let container = try decoder.singleValueContainer()

            if container.decodeNil() {
              self = .null
              return
            }
            if let value = try? container.decode(Bool.self) {
              self = .bool(value)
              return
            }
            if let value = try? container.decode(Int64.self) {
              self = .number(.integer(value))
              return
            }
            if let value = try? container.decode(Decimal.self) {
              self = .number(.decimal(value))
              return
            }
            if let value = try? container.decode(String.self) {
              self = .string(value)
              return
            }
            if let value = try? container.decode([JSONValue].self) {
              self = .array(value)
              return
            }
            if let value = try? container.decode([String: JSONValue].self) {
              self = .object(value)
              return
            }

            throw DecodingError.dataCorruptedError(
              in: container,
              debugDescription: "Unsupported JSON value."
            )
          }

          public func encode(to encoder: Encoder) throws {
            var container = encoder.singleValueContainer()

            switch self {
            case .null:
              try container.encodeNil()
            case let .bool(value):
              try container.encode(value)
            case let .number(.integer(value)):
              try container.encode(value)
            case let .number(.decimal(value)):
              try container.encode(value)
            case let .string(value):
              try container.encode(value)
            case let .array(value):
              try container.encode(value)
            case let .object(value):
              try container.encode(value)
            }
          }
        }
      }

      """

    try source.write(to: outputURL, atomically: true, encoding: .utf8)
  }
}

struct SurfaceEmitter {
  let surface: Surface
  let entry: GenerationEntry

  func emit() throws -> String {
    let schema = try SchemaNode.object(entry.schema)
    let rootSchema = schema.removingKeys(["$schema", "definitions", "title"])
    let context = TypeContext(knownTypeNames: entry.knownTypeNames)
    let declaration = try SwiftTypeRenderer(context: context).declaration(
      name: SwiftNames.type(entry.typeName),
      schema: rootSchema,
      nestedDefinitions: [:]
    )

    return """
      // Generated by codex-app-server-protocol-generator. Do not edit.
      // Source: \(entry.schemaRelativePath)

      import Foundation

      extension \(surface.generatedNamespace) {
      \(declaration.indented(by: 2))
      }

      """
  }
}
